@server = http://localhost:4004


### Notes
# @name Notes_GET
GET {{server}}/odata/v4/embedding-storage/Notes?$select=note

### Delete Notes
POST {{server}}/odata/v4/embedding-storage/deleteNotes
Content-Type: application/json

{}

### Notes
# @name Notes_POST
POST {{server}}/odata/v4/embedding-storage/Notes
Content-Type: application/json

{
  "note": "Dentist appointment on Thursday at 2 PM – don't forget to confirm."
}

###
###
POST {{server}}/odata/v4/embedding-storage/addNotes
Content-Type: application/json

{
  "notes": [
    {
      "note": "Meeting with John on Monday at 10 AM about project roadmap."
    },
    {
      "note": "Remember to buy milk, eggs, and bread on the way home."
    },
    {
      "note": "AWS EC2 instance needs to be restarted after applying updates."
    },
    {
      "note": "Read 'The Lean Startup' by Eric Ries for innovation insights."
    },
    {
      "note": "Flight to San Francisco departs at 3:45 PM on April 12th."
    }
  ]
}




### Similarity Search
@searchWord = shopping list
GET {{server}}/odata/v4/embedding-storage/similaritySearch(searchWord='{{searchWord}}')
